[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
pingora = { version = "0.4", features = ["lb"] }
async-trait = "0.1"
anyhow = "1"
axum = { version = "0.8.1" }
